# Generated by Django 5.1.1 on 2024-10-06 16:31

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=chat.models.room_photo_path)),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_room",
                        to="chat.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="chat.photo"
            ),
        ),
    ]
