# Generated by Django 5.1.1 on 2024-10-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_photo_message_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="room",
        ),
    ]
