# Generated by Django 5.1.1 on 2024-10-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_photo_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
