# Generated by Django 5.1.1 on 2024-10-09 11:31

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='photos',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to=chat.models.room_photo_path),
        ),
    ]
