# Generated by Django 5.1.1 on 2024-10-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_message_image_alter_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
