# Generated by Django 5.1.1 on 2024-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_documents_message_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
