# Generated by Django 5.1.1 on 2024-11-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_replymessage_remove_message_reply_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_message',
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='documents', to='chat.documents'),
        ),
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='photos', to='chat.photos'),
        ),
        migrations.DeleteModel(
            name='ReplyMessage',
        ),
    ]
