# Generated by Django 5.1.1 on 2024-11-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_reactiontomessage_message_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reactions',
            field=models.ManyToManyField(related_name='reactions_to_message', to='chat.reactiontomessage'),
        ),
    ]
