# Generated by Django 5.1.1 on 2024-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_message_forwarded_from_forwardedmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='reactions_to_message', to='chat.reactiontomessage'),
        ),
    ]
