# Generated by Django 5.1.1 on 2024-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_message_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo_room',
            field=models.ImageField(blank=True, default='users/default_groupChat.png', null=True, upload_to='users/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
